### ISSUE TITLE
When you tear out a stock it stays marked as a 'favourite' in the search pane

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#526]
To reproduce:

1. Search for some stocks
2. Mark them as favourite
3. Tear one out to a new window
4. Re-open the search pane. The stock that was torn out still shows as a favourite.

**Comment by owennw** [comment]
#525 Close!

**Comment by ColinEberhardt** [comment]
@bjedrzejewski beat me to it by 1 minute :-)

**Comment by WPFerg** [comment]
Closed by #543

**Comment by bjedrzejewski** [comment]
@WPFerg some regression must have happened, as this is not fixed.

**Comment by owennw** [comment]
This isn't quite the same bug.

Previously the bug was exhibiting on the search pane vanilla, and that has been fixed.

This issue is regarding when the torn out stock has previously been searched for, so is appearing as a favourite in the search results.

**Comment by bjedrzejewski** [comment]
I replicate exactly what Colin wrote:

Search for some stocks
Mark them as favourite
Tear one out to a new window
Re-open the search pane. The stock that was torn out still shows as a favourite.

And I get the bug :)

**Comment by owennw** [comment]
In that case the bug that was *fixed* is the different one!

**Comment by bjedrzejewski** [comment]
I think that's it!
